name: happydash
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - ipywidgets
  - matplotlib
  - pandas==1.2.0
  - altair>=4.1.0
  - dash==1.18.1
  - dash-core-components==1.14.1
  - dash-html-components==1.1.1
  - dash-renderer==1.8.3
  - dash-table==4.11.1
  - scikit-learn
  - statsmodels
  - pip>=20
  - black
  - flake8

